<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCdzGAJE\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCdzGAJE/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCdzGAJE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCdzGAJE\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerCdzGAJE\srcApp_KernelProdContainer([
    'container.build_hash' => 'CdzGAJE',
    'container.build_id' => '7d3e63f1',
    'container.build_time' => 1565619215,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCdzGAJE');
