<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxHbqoc\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxHbqoc/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXxHbqoc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXxHbqoc\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerXxHbqoc\srcApp_KernelProdContainer([
    'container.build_hash' => 'XxHbqoc',
    'container.build_id' => 'a3810f99',
    'container.build_time' => 1565617675,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxHbqoc');
