<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4Wy6uuX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4Wy6uuX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4Wy6uuX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4Wy6uuX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4Wy6uuX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4Wy6uuX',
    'container.build_id' => '8d3624c4',
    'container.build_time' => 1564658124,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4Wy6uuX');
