<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTQB3ifQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTQB3ifQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTQB3ifQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTQB3ifQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTQB3ifQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TQB3ifQ',
    'container.build_id' => '5acc1a27',
    'container.build_time' => 1565619863,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTQB3ifQ');
